Add versioned artifact names and update macOS target

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,31 +22,39 @@ jobs:
         uses: subosito/flutter-action@v2
       - name: Install Dependencies
         run: flutter pub get
+      - name: Extract version from pubspec.yaml
+        id: extract_version
+        run: |
+          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
+          echo "VERSION=$version" >> $GITHUB_ENV
       - name: Build MacOS
         run: flutter build macos --release
+      - name: Rename MacOS Build
+        run: |
+          cd build/macos/Build/Products
+          mv Release OpenCMS-$VERSION-macOS
+      - name: Upload Artifacts (MacOS)
+        uses: actions/upload-artifact@v4
+        with:
+          name: OpenCMS-${{ env.VERSION }}-macOS
+          path: |
+            build/macos/Build/Products/OpenCMS-${{ env.VERSION }}-macOS/
       - name: Build IPA
         run: flutter build ipa --no-codesign
-      - name: Compress Archives and IPAs
+      - name: Rename iOS Build
         run: |
           cd build
-          tar -czf ios_build.tar.gz ios
-          tar -czf macos_build.tar.gz macos
-      - name: Upload Artifacts
+          mv ios OpenCMS-$VERSION-iOS
+      - name: Upload Artifacts (iOS)
         uses: actions/upload-artifact@v4
         with:
-          name: MacOS-Release
+          name: OpenCMS-${{ env.VERSION }}-iOS
           path: |
-            build/macos_build.tar.gz
-      - name: Upload Artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: iOS-Release
-          path: |
-            build/ios_build.tar.gz
+            build/OpenCMS-${{ env.VERSION }}-iOS/
 
-  build-windows:      # Windows build job
-    name: Build & Release (Windows)  # Windows build name
-    runs-on: windows-latest # Windows environment
+  build-windows:
+    name: Build & Release (Windows)
+    runs-on: windows-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -56,16 +64,21 @@ jobs:
         run: flutter pub get
       - name: Build Windows
         run: flutter build windows --release
-      - name: Compress Windows Build
+      - name: Extract version from pubspec.yaml
+        id: extract_version
         run: |
-          cd build
-          Compress-Archive -Path windows/x64/runner/Release/ -DestinationPath windows_build.zip
+          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
+          echo "VERSION=$version" >> $GITHUB_ENV
+      - name: Rename Windows Build
+        run: |
+          cd build/windows/x64/runner
+          Rename-Item -Path "Release" -NewName "OpenCMS-$env:VERSION-Win64"
       - name: Upload Windows Artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: Windows-Releases
+          name: OpenCMS-$env:VERSION-Win64
           path: |
-            build/windows_build.zip
+            build/windows/x64/runner/OpenCMS-${{ env.VERSION }}-Win64/
 
   build-linux:
     name: Build & Release (Linux & Android)
@@ -83,28 +96,41 @@ jobs:
       - name: Install Dependencies
         run: |
           sudo apt-get update
-          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libsecret-1-dev appindicator3-0.1 libappindicator3-dev
+          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libsecret-1-dev
+          sudo apt-get install -y appindicator3-1 || echo "appindicator3-1 installation failed, continuing..."
+          sudo apt-get install -y libappindicator3-dev || echo "libappindicator3-dev installation failed, continuing..."
           flutter pub get
       - name: Build APK
         run: flutter build apk --release --split-per-abi
+      - name: Extract version from pubspec.yaml
+        id: extract_version
+        run: |
+          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
+          echo "VERSION=$version" >> $GITHUB_ENV
+      - name: Rename APK files
+        run: |
+          cd build/app/outputs/flutter-apk
+          mv app-armeabi-v7a-release.apk OpenCMS-$VERSION-armeabi-v7a.apk
+          mv app-arm64-v8a-release.apk OpenCMS-$VERSION-arm64-v8a.apk
+          mv app-x86_64-release.apk OpenCMS-$VERSION-x86_64.apk
       - name: Upload Artifacts (Android-Armeabi-v7a)
         uses: actions/upload-artifact@v4
         with:
-          name: Android-Armeabi-v7a-Release
+          name: OpenCMS-${{ env.VERSION }}-armeabi-v7a
           path: |
-            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
+            build/app/outputs/flutter-apk/OpenCMS-${{ env.VERSION }}-armeabi-v7a.apk
       - name: Upload Artifacts (Android-Arm64-v8a)
         uses: actions/upload-artifact@v4
         with:
-          name: Android-Arm64-v8a-Release
+          name: OpenCMS-${{ env.VERSION }}-arm64-v8a
           path: |
-            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
+            build/app/outputs/flutter-apk/OpenCMS-${{ env.VERSION }}-arm64-v8a.apk
       - name: Upload Artifacts (Android-X86_64)
         uses: actions/upload-artifact@v4
         with:
-          name: Android-X86_64-Release
+          name: OpenCMS-${{ env.VERSION }}-x86_64
           path: |
-            build/app/outputs/flutter-apk/app-x86_64-release.apk
+            build/app/outputs/flutter-apk/OpenCMS-${{ env.VERSION }}-x86_64.apk
       - name: Build linux
         run: flutter build linux --release
       - name: Compress Archives and APK
